# Generated by Django 4.2.7 on 2023-12-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='username', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='alias',
            field=models.CharField(default='alias', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='email', max_length=50, unique=True),
        ),
    ]
